[package]
name = "loganalyzer"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = "1.10.0"
serde_json = "1.0.138"
serde = { version = "1.0.217", features = ["derive"] }
tokio = { version = "1.41.1", features = ["full"] }
thiserror = "2.0.11"
chrono = "0.4.39"
async-trait = "0.1.86"
